### ISSUE TITLE
tailwind compatibility ?

### ISSUE THREAD

**Issue by bakman2** [vimeshjs/vimesh-style#2]
I noticed that there are no box shadows included.  Is there perhaps a comparison table of the compatibility with tailwind ? Or should it be 100% ?

**Comment by xinjie-zhang** [comment]
There are box shadows supported, shadow-md, -lg, -xl etc. Please let me know which class has problems.

**Comment by bakman2** [comment]
Sorry for the delay - not sure why it didn't show up - i got the shadow working.

But now i see another one; 

`border-x` and `border-y`

Should these be working ?

**Comment by xinjie-zhang** [comment]
You are right. border-x/y is missing. They are added in the latest version 1.1.5

**Comment by bakman2** [comment]
@xinjie-zhang would it be possible to include the tailwind filters  as well ?

**Comment by bakman2** [comment]
I was trying to fork & update the code to include filters, but I understand only a single `filter:` property can exist on a element and they would need to be combined in a single string. Is there a way to capture those and combine them ?

i had something like this

```
  // filter - saturation
  R(`saturate-`, (classDetails) => {
    let parts = classDetails.name.split("-")
    return `filter: saturate(${(+parts[1] / 200) * 2});`
  })

  // filter - hue rotate
  R(`hue-rotate-`, (classDetails) => {
    let parts = classDetails.name.split("-")
    return `filter: hue-rotate(${+parts[1]}deg);`
  })
```

but applying them both wouldnt work.

**Comment by xinjie-zhang** [comment]
Hi @bakman2  actually the filter could be implemented like transform. The basic idea is to use css vars. the R/register has the third argument initFunc : register(keys, generatorOrStyle, initFunc). It means when this class is added, it should add some init code, like the transform/filter css vars' init value.
